name: AWS-EC2 Instance CD

on:
  workflow_run:
    workflows: ["Build and Push Docker Image to Registry"]
    types: [completed]

jobs:
  on-success:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@v1.1.1
        with:
          # AWS access key id
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS secret access key
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # Where EC2 instance is
          aws-region: ${{ secrets.AWS_REGION }}
          # AWS EC2 Instance id or ids
          instance-ids: ${{ secrets.AWS_INSTANCE_ID }}
          # Command execution location
          # !!! The line below may vary depending on where your docker-compose file is located.
          working-directory: /home/ec2-user
          # Bash commands you want to execute
          command: |
            docker run -d -p 80:80 --name durianpay-test-nginx imanyauma/durianpay-test-nginx:latest